version: "3.9"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    container_name: redis
    networks:
      - slavecare_network
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
  slavecare_api:
    build:
        context: .
        dockerfile: Dockerfile
    image: "slavecare_api"
    ports:
      - "8080:80"
    env_file:
      - .env
    restart: always
    container_name: "slavecare-api"
    networks:
      - slavecare_network
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size

networks:
  slavecare_network:
    driver: bridge
