# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Lar ILPI Test Workflow

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Aslave-Care-Api.sln
    - name: Build
      run: dotnet build ./Aslave-Care-Api.sln --no-restore
    - name: Integration Tests
      run: dotnet test ./AslaveCare.IntegrationTests/AslaveCare.IntegrationTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results/IntegrationTests.trx"
    - name: Unit Tests
      run: dotnet test ./AslaveCare.UnitTests/AslaveCare.UnitTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=test-results/UnitTests.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
            ./AslaveCare.IntegrationTests/test-results/IntegrationTests.trx
            ./AslaveCare.UnitTests/test-results/UnitTests.trx